spring:
  application:
    name: your-application-name
  main:
    banner-mode: console

server:
  port: 8080

# OpenAI API key configuration
openai:
  api:
    key: "${OPENAI_API_KEY}"

# Database configuration (if needed)
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/your_db
#    username: db_user
#    password: db_pass
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

# Additional configurations can be added as needed

